const PRODUCT_KEY='lume_os_products_v1';
const MOVE_KEY='lume_os_movements_v1';
const USER_KEY='lume_os_users_v1';
const SESSION_KEY='lume_os_session_v1';
const THEME_KEY='lume_os_theme_v1';
let products=[],moves=[],users=[],currentUser=null,activeSku=null,blRows=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sku=s=>String(s||'').trim();
const qty=n=>Math.max(0,Math.floor(Number(n)||0));
const total=p=>qty(p.mediounaQty)+qty(p.socrateQty);
const admin=()=>currentUser&&currentUser.role==='admin'&&currentUser.active!==false;
const now=()=>new Date().toISOString();
const json=(raw,fb)=>{try{return JSON.parse(raw)}catch{return fb}};
function toast(msg,type=''){const t=$('toast');t.textContent=msg;t.className='toast show '+type;clearTimeout(t._x);t._x=setTimeout(()=>t.className='toast',2600)}
function save(){localStorage.setItem(PRODUCT_KEY,JSON.stringify(products));localStorage.setItem(MOVE_KEY,JSON.stringify(moves))}
function saveUsers(){localStorage.setItem(USER_KEY,JSON.stringify(users))}
async function hash(text){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('lume-os:'+text));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function email(v){return String(v||'').trim().toLowerCase()}
function id(p='id'){return p+'-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
function normalize(p){return {...p,sku:sku(p.sku),name:String(p.name||'Unnamed product').trim(),category:String(p.category||'Uncategorized').trim(),image:String(p.image||'').trim(),mediounaQty:qty(p.mediounaQty),socrateQty:qty(p.socrateQty),lowStockLimit:qty(p.lowStockLimit??2),price1:p.price1??'',price2:p.price2??'',price3:p.price3??'',attributes:p.attributes||{},custom:Boolean(p.custom)}}
function loadData(){
  const base=(window.LUME_PRODUCTS||[]).map(normalize);
  const saved=json(localStorage.getItem(PRODUCT_KEY),null);
  if(Array.isArray(saved)){
    const map=new Map(saved.map(p=>[sku(p.sku),normalize(p)]));
    const merged=base.map(p=>map.get(p.sku)||p);
    const baseSkus=new Set(base.map(p=>p.sku));
    products=[...merged,...[...map.values()].filter(p=>p.custom&&!baseSkus.has(p.sku))];
  }else products=base;
  moves=json(localStorage.getItem(MOVE_KEY),[]);
  users=json(localStorage.getItem(USER_KEY),[]);
}
async function init(){document.documentElement.dataset.theme=localStorage.getItem(THEME_KEY)||'light';loadData();bind();if(!users.length){showSetup();return}const sid=sessionStorage.getItem(SESSION_KEY);currentUser=users.find(u=>u.id===sid&&u.active!==false)||null;currentUser?showApp():showLogin()}
function showSetup(){$('authOverlay').classList.remove('hidden');$('setupPanel').classList.remove('hidden');$('loginPanel').classList.add('hidden');$('app').classList.add('hidden')}
function showLogin(){$('authOverlay').classList.remove('hidden');$('setupPanel').classList.add('hidden');$('loginPanel').classList.remove('hidden');$('app').classList.add('hidden')}
function showApp(){$('authOverlay').classList.add('hidden');$('app').classList.remove('hidden');renderAll()}
function bind(){
  $('setupBtn').onclick=createOwner;$('loginBtn').onclick=login;$('logoutBtn').onclick=()=>{sessionStorage.removeItem(SESSION_KEY);currentUser=null;showLogin()};
  $('themeBtn').onclick=()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem(THEME_KEY,n)};
  ['searchInput','categoryFilter','stockFilter'].forEach(x=>$(x).addEventListener('input',renderProducts));
  $('grid').onclick=e=>{const c=e.target.closest('.card');if(c)openProduct(c.dataset.sku)};
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
  document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
  $('confirmSaleBtn').onclick=sale;$('confirmTransferBtn').onclick=transfer;$('confirmAdjustBtn').onclick=adjust;$('saveProductBtn').onclick=saveProduct;$('deleteProductBtn').onclick=deleteProduct;
  $('receiveBtn').onclick=openReceive;$('addProductBtn').onclick=()=>openNewProduct();$('usersBtn').onclick=openUsers;
  $('blSearch').oninput=renderBlSelect;$('addBlRowBtn').onclick=addBlRow;$('saveBlBtn').onclick=saveBl;
  $('exportBtn').onclick=exportBackup;$('importInput').onchange=importBackup;$('createUserBtn').onclick=createUser;
  window.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal-shell.active').forEach(m=>closeModal(m.id))});
}
async function createOwner(){const name=$('setupName').value.trim(),em=email($('setupEmail').value),phone=$('setupPhone').value.trim(),pw=$('setupPassword').value,pw2=$('setupPassword2').value;if(!name||!em||!phone||!pw)return toast('Fill all fields');if(pw.length<8)return toast('Password minimum 8 characters');if(pw!==pw2)return toast('Passwords do not match');const u={id:id('owner'),name,email:em,phone,role:'admin',active:true,createdAt:now(),passwordHash:await hash(pw)};users=[u];saveUsers();currentUser=u;sessionStorage.setItem(SESSION_KEY,u.id);showApp();toast('Owner created')}
async function login(){const em=email($('loginEmail').value),pw=$('loginPassword').value,u=users.find(x=>email(x.email)===em&&x.active!==false);if(!u||u.passwordHash!==await hash(pw))return toast('Invalid email or password');currentUser=u;sessionStorage.setItem(SESSION_KEY,u.id);showApp();toast('Welcome '+u.name)}
function productState(p){const t=total(p),l=qty(p.lowStockLimit);return t<=0?'out':t<=l?'low':'ok'}
function filtered(){const q=$('searchInput').value.toLowerCase().trim(),cat=$('categoryFilter').value,st=$('stockFilter').value;return products.filter(p=>{if(cat!=='all'&&p.category!==cat)return false;if(st==='socrate'&&qty(p.socrateQty)<=0)return false;if(st==='mediouna'&&qty(p.mediounaQty)<=0)return false;if(st==='out'&&total(p)>0)return false;if(st==='low'&&!(total(p)<=qty(p.lowStockLimit)))return false;if(q){const attrs=Object.entries(p.attributes||{}).map(([k,v])=>k+' '+v).join(' ');if(![p.sku,p.name,p.category,p.categoriesRaw,attrs].join(' ').toLowerCase().includes(q))return false}return true})}
function renderAll(){populateCats();renderProducts();applyRole()}
function populateCats(){const val=$('categoryFilter').value||'all';const cats=[...new Set(products.map(p=>p.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b));$('categoryFilter').innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('categoryFilter').value=cats.includes(val)?val:'all'}
function renderProducts(){const list=filtered();$('grid').innerHTML=list.map(card).join('');$('empty').classList.toggle('hidden',!!list.length);$('resultInfo').textContent=`${list.length} / ${products.length} products`;$('statProducts').textContent=products.length;$('statMed').textContent=products.reduce((s,p)=>s+qty(p.mediounaQty),0);$('statSoc').textContent=products.reduce((s,p)=>s+qty(p.socrateQty),0);$('statLow').textContent=products.filter(p=>total(p)<=qty(p.lowStockLimit)).length}
function card(p){const state=productState(p);return `<article class="card" data-sku="${esc(p.sku)}"><div class="imgbox">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" onerror="this.remove()">`:'□'}<span class="badge ${state}">${state}</span></div><div class="card-body"><div class="sku">${esc(p.sku)}</div><h3>${esc(p.name)}</h3><div class="cat">${esc(p.category)}</div><div class="pills"><div><span>Med</span><b>${qty(p.mediounaQty)}</b></div><div><span>Soc</span><b>${qty(p.socrateQty)}</b></div><div class="total"><span>Total</span><b>${total(p)}</b></div></div></div></article>`}
function applyRole(){$('helloTitle').textContent=`Welcome, ${currentUser?.name||''}`;$('roleLine').textContent=admin()?'Administrator access: stock, BL, products and users.':'Sales access: view stock and sell only from Socrate.';document.body.dataset.role=admin()?'admin':'sales';document.querySelectorAll('.admin-only').forEach(el=>el.hidden=!admin())}
function find(s){return products.find(p=>sku(p.sku)===sku(s))}
function openModal(id){$(id).classList.add('active');$(id).setAttribute('aria-hidden','false')}
function closeModal(id){$(id).classList.remove('active');$(id).setAttribute('aria-hidden','true')}
function openProduct(s){const p=find(s);if(!p)return;activeSku=p.sku;$('pCat').textContent=p.category;$('pName').textContent=p.name;$('pSku').textContent=p.sku;$('pImage').innerHTML=p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:'□';$('pAttrs').innerHTML=Object.entries(p.attributes||{}).slice(0,12).map(([k,v])=>`<span>${esc(k)}: ${esc(v)}</span>`).join('');refreshProduct();['saleQty','saleNote','transferQty','transferNote','adjustQty','adjustNote'].forEach(id=>$(id).value='');$('editSku').value=p.sku;$('editName').value=p.name;$('editCategory').value=p.category;$('editImage').value=p.image;$('editLow').value=p.lowStockLimit;$('editPrice1').value=p.price1;$('editPrice2').value=p.price2;$('editPrice3').value=p.price3;switchTab('sale');openModal('productModal')}
function refreshProduct(){const p=find(activeSku);if(!p)return;$('pMed').textContent=qty(p.mediounaQty);$('pSoc').textContent=qty(p.socrateQty);$('pTot').textContent=total(p);renderHistory()}
function switchTab(tab){if(tab==='edit'&&!admin())return toast('Admin access required');document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-body').forEach(x=>x.classList.toggle('active',x.id==='tab-'+tab));if(tab==='history')renderHistory()}
function log(p,type,from,to,amount,before,after,note=''){moves.unshift({id:id('move'),sku:p.sku,name:p.name,type,from,to,quantity:qty(amount),before,after,note,date:now(),user:currentUser?.name||'',role:currentUser?.role||''})}
function before(p){return{mediounaQty:qty(p.mediounaQty),socrateQty:qty(p.socrateQty)}}
function sale(){const p=find(activeSku),q=qty($('saleQty').value);if(!p||q<=0)return toast('Enter quantity sold');if(q>qty(p.socrateQty))return toast(`No stock in Socrate. Available: ${qty(p.socrateQty)}`);const b=before(p);p.socrateQty=b.socrateQty-q;const a=before(p);log(p,'SALE','SOCRATE','CLIENT',q,b,a,$('saleNote').value.trim());save();renderProducts();refreshProduct();$('saleQty').value='';$('saleNote').value='';toast('Sale recorded')}
function transfer(){if(!admin())return toast('Admin access required');const p=find(activeSku),q=qty($('transferQty').value);if(!p||q<=0)return toast('Enter quantity');if(q>qty(p.mediounaQty))return toast(`Not enough stock in Mediouna. Available: ${qty(p.mediounaQty)}`);const b=before(p);p.mediounaQty=b.mediounaQty-q;p.socrateQty=b.socrateQty+q;const a=before(p);log(p,'TRANSFER','MEDIOUNA','SOCRATE',q,b,a,$('transferNote').value.trim());save();renderProducts();refreshProduct();toast('Transfer saved')}
function adjust(){if(!admin())return toast('Admin access required');const p=find(activeSku),hub=$('adjustHub').value,q=qty($('adjustQty').value);if(!p)return;const b=before(p);p[hub]=q;const a=before(p);log(p,'ADJUST',hub.replace('Qty','').toUpperCase(),hub.replace('Qty','').toUpperCase(),q,b,a,$('adjustNote').value.trim());save();renderProducts();refreshProduct();toast('Stock adjusted')}
function saveProduct(){if(!admin())return;const old=find(activeSku);if(!old)return;const newSku=sku($('editSku').value);if(!newSku)return toast('Reference required');if(newSku!==old.sku&&products.some(p=>p.sku===newSku))return toast('Reference already exists');old.sku=newSku;old.name=$('editName').value.trim()||old.name;old.category=$('editCategory').value.trim()||'Uncategorized';old.image=$('editImage').value.trim();old.lowStockLimit=qty($('editLow').value);old.price1=$('editPrice1').value.trim();old.price2=$('editPrice2').value.trim();old.price3=$('editPrice3').value.trim();activeSku=old.sku;save();populateCats();renderProducts();openProduct(old.sku);toast('Product saved')}
function openNewProduct(){if(!admin())return;const ref=prompt('New product reference / SKU?');if(!ref)return;if(find(ref))return toast('This reference already exists');const p=normalize({id:id('prod'),sku:ref,name:'New Product',category:'Uncategorized',custom:true,mediounaQty:0,socrateQty:0,lowStockLimit:2,attributes:{}});products.unshift(p);save();populateCats();renderProducts();openProduct(p.sku);switchTab('edit');toast('Product created')}
function deleteProduct(){if(!admin())return;const p=find(activeSku);if(!p)return;if(!confirm(`Delete ${p.name} (${p.sku})?`))return;products=products.filter(x=>x.sku!==p.sku);moves.unshift({id:id('move'),sku:p.sku,name:p.name,type:'DELETE',from:'APP',to:'TRASH',quantity:0,before:before(p),after:{mediounaQty:0,socrateQty:0},note:'Product deleted',date:now(),user:currentUser.name,role:currentUser.role});save();closeModal('productModal');populateCats();renderProducts();toast('Product deleted')}
function renderHistory(){const list=moves.filter(m=>m.sku===activeSku);$('historyList').innerHTML=list.length?list.map(m=>`<div class="move"><div class="move-top"><span class="move-type">${esc(m.type)}</span><b>${esc(m.quantity)} pcs</b><time>${new Date(m.date).toLocaleString()}</time></div><div>${esc(m.from)} → ${esc(m.to)} · ${esc(m.user)}</div><div class="muted">Before M:${m.before?.mediounaQty??'-'} S:${m.before?.socrateQty??'-'} · After M:${m.after?.mediounaQty??'-'} S:${m.after?.socrateQty??'-'}</div>${m.note?`<div class="muted">${esc(m.note)}</div>`:''}</div>`).join(''):'<p class="muted">No movements yet.</p>'}
function openReceive(){if(!admin())return;blRows=[];$('blNumber').value='';$('blDate').value=new Date().toISOString().slice(0,10);$('blHub').value='socrateQty';$('blNote').value='';$('blSearch').value='';renderBlSelect();renderBlRows();openModal('receiveModal')}
function renderBlSelect(){const q=$('blSearch').value.toLowerCase().trim();const list=products.filter(p=>!q||[p.sku,p.name,p.category].join(' ').toLowerCase().includes(q)).slice(0,80);$('blProductSelect').innerHTML=list.map(p=>`<option value="${esc(p.sku)}">${esc(p.sku)} — ${esc(p.name)} · M:${qty(p.mediounaQty)} S:${qty(p.socrateQty)}</option>`).join('')}
function addBlRow(){const s=$('blProductSelect').value;if(!s)return toast('Select a product');if(blRows.some(r=>r.sku===s))return toast('Product already in this BL');const p=find(s);blRows.push({sku:s,qty:1,name:p.name});renderBlRows()}
function renderBlRows(){$('blRows').innerHTML=blRows.length?blRows.map((r,i)=>`<div class="bl-row"><div><strong>${esc(r.sku)} — ${esc(r.name)}</strong><small>Add quantity in this BL</small></div><input type="number" min="1" step="1" value="${r.qty}" data-bl-qty="${i}"><button data-bl-del="${i}">×</button></div>`).join(''):'<p class="muted">Add products to this BL, then enter quantity for each one.</p>';document.querySelectorAll('[data-bl-qty]').forEach(x=>x.oninput=()=>{blRows[Number(x.dataset.blQty)].qty=qty(x.value)});document.querySelectorAll('[data-bl-del]').forEach(x=>x.onclick=()=>{blRows.splice(Number(x.dataset.blDel),1);renderBlRows()})}
function saveBl(){if(!admin())return;if(!blRows.length)return toast('Add at least one product');const bl=$('blNumber').value.trim()||'BL-'+Date.now(),date=$('blDate').value||new Date().toISOString().slice(0,10),hub=$('blHub').value,note=$('blNote').value.trim();let count=0;for(const r of blRows){const p=find(r.sku),q=qty(r.qty);if(!p||q<=0)continue;const b=before(p);p[hub]=qty(p[hub])+q;const a=before(p);log(p,'RECEIVE',bl,hub.replace('Qty','').toUpperCase(),q,b,a,`${date}${note?' · '+note:''}`);count++}save();closeModal('receiveModal');renderProducts();toast(`BL saved: ${count} products updated`)}
function openUsers(){if(!admin())return;renderUsers();openModal('usersModal')}
async function createUser(){if(!admin())return;const name=$('newUserName').value.trim(),em=email($('newUserEmail').value),phone=$('newUserPhone').value.trim(),role=$('newUserRole').value,pw=$('newUserPassword').value;if(!name||!em||!phone||!pw)return toast('Fill all user fields');if(pw.length<8)return toast('Password minimum 8 characters');if(users.some(u=>email(u.email)===em))return toast('Email already exists');users.push({id:id('user'),name,email:em,phone,role,active:true,createdAt:now(),passwordHash:await hash(pw)});saveUsers();['newUserName','newUserEmail','newUserPhone','newUserPassword'].forEach(id=>$(id).value='');renderUsers();toast('User created')}
function renderUsers(){$('usersList').innerHTML=users.map(u=>`<div class="user-row"><div><strong>${esc(u.name)} · ${esc(u.role)}</strong><span>${esc(u.email)} · ${esc(u.phone)} · ${u.active===false?'disabled':'active'}</span></div>${u.id===currentUser.id?'<span class="muted">You</span>':`<button data-toggle-user="${esc(u.id)}">${u.active===false?'Activate':'Disable'}</button>`}</div>`).join('');document.querySelectorAll('[data-toggle-user]').forEach(b=>b.onclick=()=>{const u=users.find(x=>x.id===b.dataset.toggleUser);if(!u)return;if(u.role==='admin'&&u.active!==false&&users.filter(x=>x.role==='admin'&&x.active!==false).length<=1)return toast('Keep one active admin');u.active=u.active===false;saveUsers();renderUsers()})}
function exportBackup(){if(!admin())return;const data={version:'lume-os-v1',products,moves,users:users.map(({passwordHash,...u})=>u),exportedAt:now()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='lume-inventory-os-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importBackup(e){if(!admin())return;const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(Array.isArray(data.products))products=data.products.map(normalize);if(Array.isArray(data.moves))moves=data.moves;save();populateCats();renderProducts();toast('Backup imported')}catch{toast('Invalid backup')}};r.readAsText(f);e.target.value=''}
init();
